### ISSUE TITLE
Crash in sample app with Intent Api

### ISSUE THREAD

**Issue by florisb** [DynamixSoftware/PrintingSample#18]
A number of functions in the sample app crash immediately when you try to use them. For example Print image.
It gives the following exception:

`E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.dynamixsoftware.printingsample, PID: 11220
    android.os.FileUriExposedException: file:///storage/emulated/0/Android/data/com.dynamixsoftware.printingsample/cache/test_page.png exposed beyond app through Intent.getData()
        at android.os.StrictMode.onFileUriExposed(StrictMode.java:1980)
        at android.net.Uri.checkFileUriExposed(Uri.java:2371)
        at android.content.Intent.prepareToLeaveProcess(Intent.java:10247)
        at android.content.Intent.prepareToLeaveProcess(Intent.java:10201)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1667)
        at android.app.Activity.startActivityForResult(Activity.java:4586)
        at android.support.v4.app.BaseFragmentActivityApi16.startActivityForResult(BaseFragmentActivityApi16.java:54)
        at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:68)
        at android.app.Activity.startActivityForResult(Activity.java:4544)
        at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:751)
        at com.dynamixsoftware.intentapi.IntentAPI.print(IntentAPI.java:162)
        at com.dynamixsoftware.printingsample.IntentApiFragment.onClick(IntentApiFragment.java:222)
        at android.view.View.performClick(View.java:6603)
        at android.view.View.performClickInternal(View.java:6576)
        at android.view.View.access$3100(View.java:780)
        at android.view.View$PerformClick.run(View.java:26090)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6702)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)`

Seems like the library uses old methods to pass files. Can this be worked around as I would like to use similar functionality in my app.

**Comment by florisb** [comment]
Found a workaround. Putting the following code in Application onCreate() fixes it:
`StrictMode.VmPolicy.Builder builder = new StrictMode.VmPolicy.Builder();
 StrictMode.setVmPolicy(builder.build());`
